sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
  - export CXX=g++-5

script:
  - $CXX -std=c++11 -o size size.cpp
  - ./size
#  - $CXX -m32 -std=c++11 -o size32 size.cpp
#  - ./size32
