sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export CXX=gcc-4.8

script:
  - $CXX -std=c++11 -o size size.cpp
  - ./size
  - $CXX -m32 -std=c++11 -o size32 size.cpp
  - ./size32
