name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: compile
      shell: bash
      run: ${CC} -march=native -o size size.cpp
      env:
        CC: ${{ matrix.cc }}
    - name: run
      run: ./size
